/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yourcompany.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 04-29-2008
 * 
 * XDoclet definition:
 * @struts.form name="gradeQueryForm"
 */
public class GradeQueryForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/** sno property */
	private String sno;

	/** year property */
	private String year;

	/** term property */
	private String term;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the sno.
	 * @return String
	 */
	public String getSno() {
		return sno;
	}

	/** 
	 * Set the sno.
	 * @param sno The sno to set
	 */
	public void setSno(String sno) {
		this.sno = sno;
	}

	/** 
	 * Returns the year.
	 * @return String
	 */
	public String getYear() {
		return year;
	}

	/** 
	 * Set the year.
	 * @param year The year to set
	 */
	public void setYear(String year) {
		this.year = year;
	}

	/** 
	 * Returns the term.
	 * @return String
	 */
	public String getTerm() {
		return term;
	}

	/** 
	 * Set the term.
	 * @param term The term to set
	 */
	public void setTerm(String term) {
		this.term = term;
	}
}