/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yourcompany.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.jspdev.biyesheji.Sc;
import com.yourcompany.struts.form.CancelScForm;

/** 
 * MyEclipse Struts
 * Creation date: 04-23-2008
 * 
 * XDoclet definition:
 * @struts.action path="/cancelSc" name="cancelScForm" input="/form/cancelSc.jsp" scope="request" validate="true"
 */
public class CancelScAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 * @throws Exception 
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws Exception {
		CancelScForm cancelScForm = (CancelScForm) form;// TODO Auto-generated method stub
		String sno=cancelScForm.getSno();
		String[] cnos=cancelScForm.getCno();
		if(cnos!=null){
		  for(int i=0;i<cnos.length;i++)
			  Sc.deleteSc(sno, cnos[i]);	
		}
		return(mapping.findForward("cancelSuccess"));
	}
}